version: 0.2

env:
  variables:
    S3_BUCKET: "soufiane-test"
    FREE_SWITCH_DIR: "/var/freeswitch"
    DEB_DIR: "/opt/freeswitch/debs"
    REPO_DIR: "/var/repo"
    DIST: "jammy"
    COMPONENT: "main"

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y build-essential git devscripts s3cmd docker.io

  build:
    commands:
      - chmod +x build-dep.sh
      - ./build-dep.sh

  post_build:
    commands:
      # Sync repository structure with new deb packages
      - mkdir -p /var/repo/dists/jammy/main/binary-amd64
      - cd  /var/repo/
      # Generate Packages.gz
      - apt-ftparchive packages pool/main > dists/jammy/main/binary-amd64/Packages
      - gzip -k dists/jammy/main/binary-amd64/Packages

      # Sync the repository with S3
      - s3cmd sync /var/repo s3://soufiane-test/repo --acl-public

      # Test the package installation in a Docker container
      - docker run --rm -v /var/repo:/repo ubuntu:22.04 /bin/bash -c "
        echo 'deb [trusted=yes] file:///repo jammy main' > /etc/apt/sources.list.d/localrepo.list;
        apt-get update;
        apt-get install -y $(ls /opt/freeswitch/debs | sed 's/_.*//')
        "

artifacts:
  files:
    - '**/*'
